### ISSUE TITLE
Youtube link icon not visible at bottom of main page, only discord icon visible(may be it happens in only dark mode)

### ISSUE THREAD

**Issue by amanat-2003** [RobertBrunhage/website#122]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by RobertBrunhage** [comment]
Doing some cleanup while I work on some changes, but can't reproduce this 
![image](https://github.com/RobertBrunhage/website/assets/26344867/954afaf7-a1e0-4bc9-9ed7-fbcea0bff944)
