### ISSUE TITLE
Font size adjustment to small screen sizes and other cosmetic issues.

### ISSUE THREAD

**Issue by Abhilash-Chandran** [RobertBrunhage/website#26]
This is just a suggestion. The font sizes for the contents in the homepage, the heading in the video page and the corresponding links looks slightly larger or in a small device. Maybe its how you would like it. 😄  If so you can close this issue.

**The solution I'd like**
I would prefer to have the fonts adjusted to the screen size or maybe using a screen size ratio like the ones used in Bootstrap.  Especially the landing page. 

**Alternatives**
Maybe you could choose a size that is not too large in small screens and not too small large screens. Then there isn't much changes needed.

A short video of what is happening now.

https://user-images.githubusercontent.com/4489849/105836002-e41cec80-5fcc-11eb-8281-414ef15cf991.mp4

**Unrelated issues:**

* The first link in the read me is unreachable.
* The about link in the github perhaps needs an update.

**Comment by RobertBrunhage** [comment]
Thanks for taking the time @Abhilash-Chandran! 👌

We will add this to the upcoming design changes, when the design in complete. If you right click the first link and open in icognito is it still unreachable? Tried it myself and seems to be working fine.

**Comment by Abhilash-Chandran** [comment]
Its a pleasure.

It this link I am talking about. Doesn't work in incognito as well.

![image](https://user-images.githubusercontent.com/4489849/105840546-74f6c680-5fd3-11eb-8cc2-4e7c45215fcb.png)


This leads to some thing like the following which is not valid.

https://github.com/RobertBrunhage/website/blob/master/www.robertbrunhage.com

**Comment by RobertBrunhage** [comment]
#27

**Comment by RobertBrunhage** [comment]
Fixed with #25
