### ISSUE TITLE
Add space between "Email text Field" and "Notify me button"

### ISSUE THREAD

**Issue by isaacadariku** [RobertBrunhage/website#41]
**Describe the bug**
The notify me button looks like its stack on the email text field on my desktop, it needs addition space in between or reducing of the text field.

**To Reproduce**
1. Go to https://robertbrunhage.com/
2. Scroll down to 2nd Section
3. See the error

**Screenshots**
![rb](https://user-images.githubusercontent.com/46024202/107873548-a5839f00-6eb3-11eb-86ea-1bf951c0d79f.PNG)

**Desktop:**
 - OS: - Windows
 - Browser - chrome
 - Version  88.0.4324.150

**Comment by RobertBrunhage** [comment]
Thanks for noting it, it will be part of #25!
