### ISSUE TITLE
Conditionally show the code button depending on github link in blogpost

### ISSUE THREAD

**Issue by fadhilsaheer** [RobertBrunhage/website#57]
![code](https://user-images.githubusercontent.com/67850930/115195153-088bef00-a10c-11eb-9214-9e1350949593.PNG)

**Comment by RobertBrunhage** [comment]
Oh haven't notice that, that is pretty severe. I should link to the code which I link in the blogpost.

cc @JohnHilding

**Comment by RobertBrunhage** [comment]
Nvm this one seems to work, it's just that not all blogposts have a code link in the markdown. So in this case the code button should not be there for some posts.

**Comment by fadhilsaheer** [comment]
ok ! 
> I was wondering and looking at that why would he need that button in a blog 😂
